# system_of_the_db/init.py
import sys
import os


from .consructor import *

db = SystemOfDb()
info_manager = InfoManager(db)

TOURISTS = [
    ("Ana López", "ES123456", "España"),
    ("Carlos Mendoza", "MX789012", "México"),
    ("Sophie Dubois", "FR345678", "Francia"),
    ("Hiroshi Tanaka", "JP901234", "Japón"),
    ("Liam O'Connor", "IE567890", "Irlanda")
]

CARS = [
    ("ABC123", "Toyota", "Corolla", "Rojo", "disponible"),
    ("XYZ789", "Honda", "Civic", "Azul", "disponible"),
    ("DEF456", "Ford", "Focus", "Blanco", "disponible"),
    ("GHI012", "Volkswagen", "Golf", "Gris", "disponible"),
    ("JKL345", "BMW", "Serie 3", "Negro", "disponible"),
    ("MNO678", "Mercedes", "C-Class", "Plateado", "disponible"),
    ("PQR901", "Audi", "A4", "Rojo", "disponible"),
    ("STU234", "Hyundai", "Elantra", "Azul", "disponible"),
    ("VWX567", "Nissan", "Sentra", "Blanco", "disponible"),
    ("YZA890", "Chevrolet", "Cruze", "Gris", "disponible"),
    ("BCD234", "Toyota", "Camry", "Negro", "disponible"),
    ("EFG567", "Honda", "Accord", "Blanco", "disponible"),
    ("HIJ890", "Ford", "Mustang", "Rojo", "disponible"),
    ("KLM123", "Volkswagen", "Passat", "Azul", "disponible"),
    ("NOP456", "BMW", "X3", "Gris", "disponible"),
    ("QRS789", "Mercedes", "GLC", "Negro", "disponible"),
    ("TUV012", "Audi", "Q5", "Blanco", "disponible"),
    ("WXY345", "Hyundai", "Tucson", "Rojo", "disponible"),
    ("ZAB678", "Nissan", "Rogue", "Azul", "disponible"),
    ("CDE901", "Chevrolet", "Equinox", "Gris", "disponible"),
    ("FGH234", "Toyota", "RAV4", "Negro", "disponible"),
    ("IJK567", "Honda", "HR-V", "Blanco", "disponible"),
    ("LMN890", "Ford", "Ranger", "Rojo", "disponible"),
    ("OPQ123", "Volkswagen", "Tiguan", "Azul", "disponible"),
    ("RST456", "BMW", "X5", "Gris", "disponible"),
    ("UVW789", "Mercedes", "GLE", "Negro", "disponible"),
    ("XYZ012", "Audi", "Q7", "Blanco", "disponible"),
    ("ABC345", "Kia", "Forte", "Rojo", "disponible"),
    ("DEF678", "Kia", "Sportage", "Azul", "disponible"),
    ("GHI901", "Mazda", "3", "Gris", "disponible"),
    ("JKL234", "Mazda", "CX-5", "Negro", "disponible"),
    ("MNO567", "Subaru", "Impreza", "Blanco", "disponible"),
    ("PQR890", "Subaru", "Forester", "Rojo", "disponible"),
    ("STU123", "Tesla", "Model 3", "Azul", "disponible"),
    ("VWX456", "Tesla", "Model Y", "Gris", "disponible"),
    ("YZA789", "Peugeot", "308", "Negro", "disponible"),
    ("BCD012", "Peugeot", "3008", "Blanco", "disponible"),
    ("EFG345", "Renault", "Megane", "Rojo", "disponible"),
    ("HIJ678", "Renault", "Duster", "Azul", "disponible"),
    ("KLM901", "Fiat", "Tipo", "Gris", "disponible"),
    ("NOP234", "Fiat", "500X", "Negro", "disponible"),
    ("QRS567", "Suzuki", "Swift", "Blanco", "disponible"),
    ("TUV890", "Suzuki", "Vitara", "Rojo", "disponible"),
    ("WXY123", "Lexus", "ES", "Azul", "disponible"),
    ("ZAB456", "Lexus", "RX", "Gris", "disponible"),
    ("CDE789", "Volvo", "XC40", "Negro", "disponible"),
    ("FGH012", "Volvo", "XC60", "Blanco", "disponible"),
    ("IJK345", "Toyota", "Hilux", "Rojo", "disponible"),
    ("LMN678", "Chevrolet", "Tahoe", "Azul", "disponible"),
    ("OPQ901", "Ford", "Explorer", "Gris", "disponible"),
    ("RST234", "Honda", "Pilot", "Negro", "disponible"),
    ("UVW567", "Nissan", "Pathfinder", "Blanco", "disponible"),
    ("XYZ890", "Hyundai", "Santa Fe", "Rojo", "disponible"),
    ("ABC124", "Kia", "Sorento", "Azul", "disponible"),
    ("DEF457", "Mazda", "CX-9", "Gris", "disponible"),
    ("GHI780", "Subaru", "Outback", "Negro", "disponible"),
    ("JKL013", "Volkswagen", "Atlas", "Blanco", "disponible"),
    ("MNO346", "Toyota", "4Runner", "Rojo", "disponible"),
    ("PQR679", "Honda", "Odyssey", "Azul", "disponible"),
    ("STU902", "Chrysler", "Pacifica", "Gris", "disponible"),
    ("VWX235", "Dodge", "Charger", "Negro", "disponible"),
    ("YZA568", "Jeep", "Wrangler", "Blanco", "disponible"),
    ("BCD891", "Jeep", "Grand Cherokee", "Rojo", "disponible"),
    ("EFG124", "Land Rover", "Range Rover", "Azul", "disponible"),
    ("HIJ457", "Jaguar", "F-Pace", "Gris", "disponible"),
    ("KLM780", "Porsche", "Cayenne", "Negro", "disponible"),
    ("NOP013", "Porsche", "Macan", "Blanco", "disponible"),
    ("QRS346", "BMW", "Serie 5", "Rojo", "disponible"),
    ("TUV679", "Audi", "A6", "Azul", "disponible"),
    ("WXY902", "Mercedes", "E-Class", "Gris", "disponible"),
    ("ZAB235", "Lexus", "GS", "Negro", "disponible"),
    ("CDE568", "Infiniti", "Q50", "Blanco", "disponible"),
    ("FGH891", "Acura", "TLX", "Rojo", "disponible"),
    ("IJK124", "Cadillac", "CT5", "Azul", "disponible"),
    ("LMN457", "Lincoln", "Nautilus", "Gris", "disponible"),
    ("OPQ780", "Genesis", "G80", "Negro", "disponible"),
    ("RST013", "Buick", "Enclave", "Blanco", "disponible"),
    ("UVW346", "GMC", "Yukon", "Rojo", "disponible"),
    ("XYZ679", "RAM", "1500", "Azul", "disponible"),
    ("ABC902", "Toyota", "Tacoma", "Gris", "disponible"),
    ("DEF235", "Chevrolet", "Silverado", "Negro", "disponible"),
    ("GHI568", "Ford", "F-150", "Blanco", "disponible"),
    ("JKL891", "Honda", "CR-V", "Rojo", "disponible"),
    ("MNO124", "Nissan", "Altima", "Azul", "disponible"),
    ("PQR457", "Hyundai", "Sonata", "Gris", "disponible"),
    ("STU780", "Kia", "K5", "Negro", "disponible"),
    ("VWX013", "Mazda", "6", "Blanco", "disponible"),
    ("YZA346", "Subaru", "Legacy", "Rojo", "disponible"),
    ("BCD679", "Volkswagen", "Jetta", "Azul", "disponible"),
    ("EFG902", "Toyota", "Avalon", "Gris", "disponible"),
    ("HIJ235", "Honda", "Insight", "Negro", "disponible"),
    ("KLM568", "Toyota", "Prius", "Blanco", "disponible"),
    ("NOP891", "Chevrolet", "Bolt", "Rojo", "disponible"),
    ("QRS124", "Nissan", "Leaf", "Azul", "disponible"),
    ("TUV457", "Hyundai", "Kona Electric", "Gris", "disponible"),
    ("WXY780", "Kia", "Niro EV", "Negro", "disponible"),
    ("ZAB013", "Ford", "Mach-E", "Blanco", "disponible"),
    ("CDE346", "Volkswagen", "ID.4", "Rojo", "disponible"),
    ("FGH679", "Audi", "e-tron", "Azul", "disponible"),
    ("IJK902", "BMW", "i4", "Gris", "disponible"),
    ("LMN235", "Mercedes", "EQC", "Negro", "disponible"),
    ("OPQ568", "Tesla", "Model S", "Blanco", "disponible"),
    ("RST891", "Tesla", "Model X", "Rojo", "disponible")
]


COUNTRIES = [
    "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", 
    "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", 
    "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", 
    "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", 
    "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", 
    "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", 
    "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", 
    "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", 
    "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea", 
    "Guinea ecuatorial", "Guinea-Bisáu", "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", 
    "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", 
    "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", 
    "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", 
    "Malasia", "Malaui", "Maldivas", "Mali", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", 
    "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", 
    "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", 
    "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", 
    "República Centroafricana", "República Checa", "República Democrática del Congo", "República del Congo", 
    "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", 
    "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", 
    "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Sudáfrica", "Sudán", "Sudán del Sur", 
    "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", 
    "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", 
    "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue"
]